package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSpaceApplyWritesCreate represents a create object
type NetworkHabitatSpaceApplyWritesCreate struct {
	LexiconTypeID string      `json:"$type"`
	Action        string      `json:"action"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#create" before encoding.
func (t NetworkHabitatSpaceApplyWritesCreate) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#create"
	type alias NetworkHabitatSpaceApplyWritesCreate
	return json.Marshal(alias(t))
}

// NetworkHabitatSpaceApplyWritesInput represents the input for network.habitat.space.applyWrites
type NetworkHabitatSpaceApplyWritesInput struct {
	Repo     string                                 `json:"repo"`
	Space    string                                 `json:"space"`
	Validate bool                                   `json:"validate,omitempty"`
	Writes   []NetworkHabitatSpaceApplyWritesCreate `json:"writes"`
}

// NetworkHabitatSpaceApplyWritesOutput represents the output for network.habitat.space.applyWrites
type NetworkHabitatSpaceApplyWritesOutput struct {
	Results []NetworkHabitatSpaceApplyWritesResult `json:"results"`
}

// NetworkHabitatSpaceApplyWritesResult represents a result object
type NetworkHabitatSpaceApplyWritesResult struct {
	LexiconTypeID string `json:"$type"`
	Cid           string `json:"cid"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#result" before encoding.
func (t NetworkHabitatSpaceApplyWritesResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#result"
	type alias NetworkHabitatSpaceApplyWritesResult
	return json.Marshal(alias(t))
}
